### ISSUE TITLE
Invalid user should respond with 422 instead of 404

### ISSUE THREAD

**Issue by viniciuszago** [fidelisrafael/nifty_services#30]
As I see here, it should be an `unprocessable_entity` error instead of `not_found`, because it is a create action and doesn't make sense to check if user is not found to create it.

https://github.com/fidelisrafael/nifty_services#alien-invalid-user-

You must have the following keys setup up in your locales files:

```yml
 nifty_services:
   users:
     not_found: "Invalid or not found user"
     ip_temporarily_blocked: "This IP is temporarily blocked from creating records"
   # note: posts is the key return in `record_error_key` service method
   posts:
      user_cant_create: "User cant create this record"
```

#### :alien: Invalid user <a name="create-resource-user-invalid"></a>

If you try to create a post for a invalid user, such as:

```ruby
# PostCreateService.new(user, options)
service = PostCreateService.new(nil, options)
service.execute

service.success? # false
service.response_status # :not_found
service.response_status_code # 404
service.errors # ["Invalid or not found user"]
```
